services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1
      - MYSQL_DATABASE=mydb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
  python-app:
    build: .    
    image: dinner_py-mysql:v0.1
    container_name: python-app
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql-db
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=1
      - MYSQL_DATABASE=mydb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql-db
      - PMA_USER=root
      - PMA_PASSWORD=1

volumes:
  mysql-data: